<?php
/**
 * Opulence
 *
 * @link      https://www.opulencephp.com
 * @copyright Copyright (C) 2016 David Young
 * @license   https://github.com/opulencephp/Opulence/blob/master/LICENSE.md
 */
namespace Opulence\QueryBuilders\Conditions;

/**
 * The condition 
 */
interface ICondition
{
    /**
     * Gets the parameters bound by the condition
     * 
     * @return array The list of parameters
     */
    public function getParameters() : array;
    
    /**
     * Gets the SQL generated by the condition
     * 
     * @return string The SQL
     */
    public function getSql() : string;
}